### ISSUE TITLE
module 'math' has no attribute 'tau'

### ISSUE THREAD

**Issue by Andree12** [MeltyPlayer/OoT3D-Importer#3]
```
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\__init__.py", line 48, in execute
    return load_zar(self, context)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\import_zar.py", line 65, in load_zar
    i == 0 # Clear armatures
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\import_csab.py", line 128, in import_anims
    quaternion = getQuaternionCsab(self.csab_parsed, cmb_bone, i)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\utils.py", line 129, in getQuaternionCsab
    rotationX = sampleAnimationTrackRotation(node.rotationX, animFrame)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\csab2.py", line 403, in sampleAnimationTrackRotation
    return sampleAnimationTrackHermiteRotation(track, frame)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\csab2.py", line 358, in sampleAnimationTrackHermiteRotation
    r1 = r0 + differenceInRadians(r1, r0)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_cmb-master\csab2.py", line 331, in differenceInRadians
    return ((((lhs - rhs) % math.tau) + (math.tau + math.pi)) % math.tau) - math.pi
AttributeError: module 'math' has no attribute 'tau'
```
Got this error when I import a zar file with animations. The version of Blender I used is 2.79b.

**Comment by Alvin9301** [comment]
What model did you try importing into Blender?

**Comment by Andree12** [comment]
> What model did you try importing into Blender?

All of the models

**Comment by Andree12** [comment]
#4

**Comment by MeltyPlayer** [comment]
Oops, looks like this might not be in all versions of Python's math library. It's simple to just switch to 2 * pi instead so I just pushed out a fix.
